config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :emails
  resources :partners
  resources :users

  root 'users#new'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :partner
  has_many :emails
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1
  # PATCH/PUT /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to relationships_url, notice: 'Relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_params
      params[:relationship]
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Relationships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= link_to 'Show', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>